vich_uploader:
    db_driver: orm

    mappings:
       products:
           uri_prefix: /images/products
           upload_destination: '%kernel.project_dir%/public/assets/img'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
